# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0f9h6SSkH6iOZXrM-yfqNvEJiF9AN5o
"""

from PIL import Image
import numpy as np

# -----------------------------
# 1. Read Image and Convert to RGB Array
# -----------------------------

# Load image (replace with your image path)
img = Image.open("101.jpg")
img = img.convert("RGB")

# Convert to RGB matrix (H x W x 3)
rgb_array = np.array(img)
print("Original RGB shape:", rgb_array.shape)


# -----------------------------
# 2. Compress Image into 16 x 16 Grid
# -----------------------------

img_16 = img.resize((16, 16))
rgb_16 = np.array(img_16)
print("16x16 RGB shape:", rgb_16.shape)


# -----------------------------
# 3. Sliding Pooling Function
# -----------------------------

def sliding_pooling(image, pool_size=2, stride=1, mode="max"):
    H, W, C = image.shape
    out_h = (H - pool_size) // stride + 1
    out_w = (W - pool_size) // stride + 1

    output = np.zeros((out_h, out_w, C))

    for i in range(out_h):
        for j in range(out_w):
            h_start = i * stride
            w_start = j * stride

            window = image[
                h_start:h_start + pool_size,
                w_start:w_start + pool_size,
                :
            ]

            if mode == "max":
                output[i, j] = np.max(window, axis=(0, 1))
            elif mode == "min":
                output[i, j] = np.min(window, axis=(0, 1))
            elif mode == "avg":
                output[i, j] = np.mean(window, axis=(0, 1))

    return output


# -----------------------------
# 4. Apply Sliding Min / Max / Avg Pooling
# -----------------------------

max_pooled = sliding_pooling(rgb_16, pool_size=2, stride=1, mode="max")
min_pooled = sliding_pooling(rgb_16, pool_size=2, stride=1, mode="min")
avg_pooled = sliding_pooling(rgb_16, pool_size=2, stride=1, mode="avg")

print("Max pooled shape:", max_pooled.shape)
print("Min pooled shape:", min_pooled.shape)
print("Avg pooled shape:", avg_pooled.shape)


# -----------------------------
# 5. Display Sample Values
# -----------------------------

print("\nSample RGB values from 16x16 image:")
print(rgb_16[0][0])

print("\nSample Max pooled value:")
print(max_pooled[0][0])

print("\nSample Min pooled value:")
print(min_pooled[0][0])

print("\nSample Avg pooled value:")
print(avg_pooled[0][0])